Global:
  ManageImages: true 
  BootMountPoint: /boot/efi
Components:
  Enabled: false 
EFI:
  ImageDir: /boot/efi/EFI/zbm
  Versions: false
  Enabled: true 
Kernel:
  CommandLine: ro quiet loglevel=4 zbm.timeout=2 zbm.prefer=zroot!!
