#!/usr/bin/env sh

UID="1000"
USER=$(getent passwd "$UID" | cut -d: -f1)
HOME=$(getent passwd "$UID" | cut -d: -f6)

groups="$(id -Gn "$USER" | tr ' ' ':')"
svdir="$HOME/.local/share/service"

exec chpst -u "$USER:$groups" runsvdir "$svdir"
